# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kuflu/Vivado/VivadoProjects/FMCW/FMCW.srcs/sources_1/ip/FFT0/FFT0.xci
# IP: The module: 'FFT0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuflu/Vivado/VivadoProjects/FMCW/FMCW.gen/sources_1/ip/FFT0/FFT0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/VivadoProjects/FMCW/FMCW.srcs/sources_1/ip/FFT0/FFT0.xci
# IP: The module: 'FFT0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuflu/Vivado/VivadoProjects/FMCW/FMCW.gen/sources_1/ip/FFT0/FFT0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
